server:
  tomcat.uri-encoding: UTF-8
  port: 8182

spring:
  application:
      name: redis-manager
  http:
      encoding:
        enabled: true
        force: true
        charset: UTF-8
  # 改成自己的数据库，仅需自己创建数据库即可，相关表会自动生成
  datasource:
      name: serverbase
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.16.50.209:4000/redis_manager?useUnicode=true&characterEncoding=utf-8
      username: root
      password:

  # 如果使用微信报警，填写微信企业号相关信息
  wechat:

  # 如果使用邮件报警，在此处开启开关并配置log4j邮件相关信息
  mail:
     alarm: false
     SMTPHost: xx.xx.xx.xx
     SMTPUsername:
     SMTPPassword:
     mailFrom: xxx@qq.com
     mailTo: xxx@qq.com

mybatis:
  mapper-locations: classpath*:mappers/*
  configuration:
      mapUnderscoreToCamelCase: true

cache:
    # redis 客户端用于配置修改什么的,记得安装部署的时候要修改一下权限 chmod 777 redis-cli
    redis.client: ../redis-manager/src/main/resources/public/shell/redis-cli
    # userapi自动生成 restful 接口,开发时配置 : ../redis-manager/src/main/resources/public/core/userApi.js
    user.api.path:
    # 自动生成 mysql 表
    mysql:
        scan.package: com.newegg.ec.cache
        # 配置成跟 jdbc 连接的信息一样
        database.name: redis_manager
        # 用于删除 7 天的后的数据
        clearn.day: 7
    # 支持的插件多个可以用逗号隔开
    plugin: machine,docker
    # humpback 相关配置
    humpback:
        # 镜像列表, 如果没有humpback，则可为空
        image:
        # humpback 操作的 api 接口 %s 是占位符
        api.format: http://%s:8500/dockerapi/v2/
    # docker 相关配置
    docker:
        # docker 镜像需要自己 build
        image: reasonduan/redis:4.0.12-alpine,reasonduan/redis:5.0.3-alpine
      # docker api 格式
        api.format: http://%s:2375/
    # 物理机相关配置
    machine:
        install:
            # 安装脚本的路径
            shell: /shell/redis_install.sh
            # 安装包路径
            package: /package
            # 安装的基础路径
            basepath: redis-cluster/
        # 可以安装的 tar 包
        image: redis-4.0.10.tar,redis-5.0.2.tar,redis3.0.6.tar

