server:
  tomcat.uri-encoding: UTF-8
  port: 8182

spring:
  application:
      name: redis-manager
  http:
      encoding:
        enabled: true
        force: true
        charset: UTF-8
  datasource:
      name: serverbase
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.16.46.170:3306/redis_manager_new?useUnicode=true&characterEncoding=utf-8
      username: test
      password: test

mybatis:
  mapper-locations: classpath*:mappers/*
  configuration:
      mapUnderscoreToCamelCase: true

cache:
    user.api.path: ../redis-manager/target/classes/public/core/userApi.js
    mysql.scan.package: com.newegg.ec.cache
    humpback:
        image: humpback-hub.newegg.org/shec/redis3.0.6:v3,docker.neg/shec/redis-4.0.8:v1
        api.format: http://%s:8500/dockerapi/v2/
    docker:
            image: ssecbigdata02:5000/redis4.0.1
            api.format: http://%s:2375/
    machine:
        install:
            shell: /shell/redis_install.sh
            package: /package
            basepath: redis-cluster/
        image: redis3.0.6.tar

